# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  myfirst:
    image: myfirst
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5202:5202
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
